version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "15731:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "10805:1080"
###< symfony/mailer ###
